### ISSUE TITLE
Generated openssl serial number may be odd

### ISSUE THREAD

**Issue by youennf** [w3c/wpt-tools#86] opened 2016-06-30 07:25 UTC
WebKit bots seem to dislike this change: https://github.com/w3c/wpt-tools/commit/b388d6b14df8acc3fad070c74b435cd7aff056d1

See https://build.webkit.org/results/Apple%20Yosemite%20Release%20WK1%20(Tests)/r202508%20(15787)/wptwk_process_log.out.txt, the serial having an odd number of characters: 
https://build.webkit.org/results/Apple%20Yosemite%20Release%20WK1%20(Tests)/r202508%20(15787)/_wpt_certs/serial

Related bug entry is https://bugs.webkit.org/show_bug.cgi?id=159166

**Comment by jgraham** [comment] 2016-06-30 07:59
Dupe of #85 I think.

**Closed by jgraham** 2016-06-30 07:59 UTC
